methods:
  - name: "GT"
    path: "/home/Results/GT/data_000000/"
    is_gt: true
  - name: "Ours"
    path: "/home/Results/Ours/data_000000/"
    is_ours: true
  - name: "Method1"
    path: "/home/Results/Method1/data_000000/"
  - name: "Method2"
    path: "/home/Results/Method2/data_000000/"
  - name: "Method3"
    path: "/home/Results/Method3/data_000000/"
  - name: "Method4"
    path: "/home/Results/Method4/data_000000/"

visualization_path: "visualization"
make_variance_map: false
make_ranking_map: false

# IMPORTANT
# Setting clear_previous will clear all previous cut_positions.txt, delete all files in output_crop_path and delete the PPT file in output_ppt_path! 
clear_previous: true
output_info_path: "./cut_positions.txt"
output_crop_path: "crop_img" # Saves all cropped patches in here
output_ppt_path: "./output.pptx"
show_crop_alert: false
display_rows: 2
display_cols: 2

# Configs for image cropping
crop_box_colors: ["red", "green", "blue", "yellow", "cyan", "magenta"]
patch_border_width: 2
box_border_width: 2

# Configs for PPT generation
placeholder_path: "icon.png"
output_ppt_path: "output.pptx"
small_cnt: 3 # 每张大图下面放的放大图数量
groups_per_page: 5 # 每页贴几组图
# A4大小
slide_w: 210
slide_h: 297
group_hori_gap_ratio: 0.05 # 每组之间横向间隔和每组横向宽度的比值
group_vert_gap_ratio: 0.07 # 每组之间纵向间隔和每组纵向宽度的比值
small_hori_gap_ratio: 0.05 # 小图-大图之间横向距离 / 小图宽度
small_vert_gap_ratio: 0.05 # 小图-小图之间纵向距离 / 小图高度